/**
 * Description - Object that store data for the quiz
 * @type {Array} - Array of objects
 */
const quizQuestionsData = [
  {
    id: 1,
    points: 2,
    category: "HTML",
    questionTitle: "Хөвөнг юунаас гаргаж авдаг вэ? ",
    correctAnswer: "Мод",
    incorrectAnswers: ["Хөөсөнцөр"],
  },
  {
    id: 2,
    points: 3,
    category: "HTML",
    questionTitle: " “Хурдан борлог морины эзэн” зохиолыг хэн бичсэн бэ?",
    correctAnswer: "Ч. Лодойдамба",
    incorrectAnswers: ["Д.Нацагдорж"],
  },
  {
    id: 3,
    points: 4,
    category: "JavaScript",
    questionTitle: "Дуба сохор дундаа ганц нүдтэй тэр юу вэ?",
    correctAnswer: "Зүү, тэвнэ",
    incorrectAnswers: ["Галын амсар"],
  },
  {
    id: 4,
    points: 4,
    category: "CSS",
    questionTitle: " МУ-ын хамгийн том газар нутагтай аймаг?",
    correctAnswer: "Өмнөговь",
    incorrectAnswers: ["Хэнтий"],
  },
  {
    id: 5,
    points: 5,
    category: "Bootstrap",
    questionTitle: "Ингэний сүүгээр хийсэн ундаа?",
    correctAnswer: "Хоормог",
    incorrectAnswers: ["Айраг"],
  },
  {
    id: 6,
    points: 8,
    category: "Git",
    questionTitle: " Богдхан уул хэдэн амтай вэ? ",
    correctAnswer: "32",
    incorrectAnswers: ["22"],
  },
  {
    id: 7,
    points: 5,
    category: "UI/UX",
    questionTitle: " Тэмээ усаа хаанаа нөөцөлдөг вэ?",
    correctAnswer: "Бөх",
    incorrectAnswers: ["Ходоод"],
  },
  {
    id: 8,
    points: 9,
    category: "JavaScript",
    questionTitle: " Дэлхийн хэдэн хувийг ус эзэлдэг вэ?",
    correctAnswer: "71%",
    incorrectAnswers: ["70%"],
  },
  {
    id: 9,
    points: 6,
    category: "Bootstrap",
    questionTitle: " Аалз хэдэн хөлтэй вэ? ",
    correctAnswer: "8",
    incorrectAnswers: ["4"],
  },
  {
    id: 10,
    points: 10,
    category: "CSS",
    questionTitle: " Шилийг юунаас гарган авдаг вэ?",
    correctAnswer: "Элс",     
    incorrectAnswers: ["Хар шороо"],
  },
  {
    id: 11,
    points: 7,
    category: "JavaScript",
    questionTitle: "Цэнхэр, шар өнгөний дундаас ямар өнгө гардаг вэ?",
    correctAnswer: "Ногоон",
    incorrectAnswers: ["Улаан"],
  },
  {
    id: 12,
    points: 5,
    category: "UI/UX",
    questionTitle: "Ямар амьтныг монгол бичигт “мэнэхэй” гэж бичдэг вэ?",
    correctAnswer: "Мэлхий",
    incorrectAnswers: ["Мануухай"],
  },
  {
    id: 13,
    points: 1,
    category: "HTML",
    questionTitle: "Загас яагаад нүдээ аньдаггүй вэ?",
    correctAnswer: "Аньсагагүй учир",
    incorrectAnswer: ["Усанд байгаа учир"],
  },
  {
    id: 14,
    points: 2,
    category: "CSS",
    questionTitle: "Дэлхийн хамгийн чийглэг улс?",
    correctAnswer: "Энэтхэг",
    incorrectAnswers: ["Солонгос"],
  },
  {
    id: 15,
    points: 8,
    category: "Git",
    questionTitle: "Эрдэнэзуугийн хийд хэдэн суваргатай вэ?",
    correctAnswer: "108",
    incorrectAnswers: ["300"],
  },
  {
    id: 16,
    points: 7,
    category: "CSS",
    questionTitle: " “Дацан” гэж юуг хэлдэг вэ?",
    correctAnswer: "Лам хуврагийн сургууль",
    incorrectAnswers: ["Дарцаг"],
  },
  {
    id: 17,
    points: 3,
    category: "Bootstrap",
    questionTitle: "Айлд орсон хүн яаж суухыг цээрлэдэг вэ?",
    correctAnswer: "Цомцойж буюу явган",
    incorrectAnswers: ["container"],
  },
  {
    id: 18,
    points: 10,
    category: "UI/UX",
    questionTitle: " “Газар шороондоо би хайртай” шүлгийн зохиогч?",
    correctAnswer: "Ш.Дулмаа",
    incorrectAnswers: ["Д.Нацагдорж"],
  },
  {
    id: 19,
    points: 3,
    category: "CSS",
    questionTitle: "Сая төллөсөн эх малын хөхнөөс гарах шим тэжээлийг юу гэдэг вэ?",
    correctAnswer: "Гал уураг",
    incorrectAnswers: ["Сүү"],
  },
];
